import Image from "next/image";

export default function Hero() {
  return (
      <section className="relative min-h-screen flex items-center justify-center overflow-hidden">

            <Image
                    src="/images/van.png"
                            alt="Bobby's Super Whip Ice Cream Van"
                                    fill
                                            priority
                                                    className="object-cover object-[55%_center]"
                                                          />

                                                                <div className="absolute inset-0 bg-black/55" />

                                                                      <div className="relative z-10 max-w-5xl mx-auto px-6 py-20 text-center text-white">

                                                                              <span className="inline-block rounded-full bg-sky-500 px-5 py-2 text-sm font-semibold tracking-wide shadow-lg">
                                                                                        ⭐ Serving the Midlands Since 2016
                                                                                                </span>

                                                                                                        <h1 className="mt-8 text-4xl sm:text-5xl lg:text-7xl font-extrabold leading-tight">
                                                                                                                  It's Not A Dream...
                                                                                                                            <br />
                                                                                                                                      <span className="text-cyan-300">
                                                                                                                                                  It's Bobby's Ice Cream!
                                                                                                                                                            </span>
                                                                                                                                                                    </h1>

                                                                                                                                                                            <p className="mt-6 max-w-3xl mx-auto text-lg sm:text-xl text-gray-200 leading-relaxed">
                                                                                                                                                                                      Premium Whippy Ice Cream, Luxury Sundaes and Ice Cold Slush served
                                                                                                                                                                                                across Walsall and the West Midlands for weddings, schools,
                                                                                                                                                                                                          birthdays, corporate events and private parties.
                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                          <div className="mt-10 flex flex-col sm:flex-row gap-4 justify-center">
                                                                                                                                                                                                                                    <a
                                                                                                                                                                                                                                                href="#booking"
                                                                                                                                                                                                                                                            className="rounded-full bg-cyan-500 px-8 py-4 text-lg font-bold hover:bg-cyan-400 transition"
                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                  Book Your Event
                                                                                                                                                                                                                                                                                            </a>

                                                                                                                                                                                                                                                                                                      <a
                                                                                                                                                                                                                                                                                                                  href="#gallery"
                                                                                                                                                                                                                                                                                                                              className="rounded-full border-2 border-white px-8 py-4 text-lg font-bold hover:bg-white hover:text-black transition"
                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                    View Gallery
                                                                                                                                                                                                                                                                                                                                                              </a>
                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                              <div className="mt-16 grid gap-6 md:grid-cols-3">

                                                                                                                                                                                                                                                                                                                                                                                        <div className="rounded-3xl bg-white/10 backdrop-blur-md p-6">
                                                                                                                                                                                                                                                                                                                                                                                                    <div className="text-5xl">🍦</div>
                                                                                                                                                                                                                                                                                                                                                                                                                <h3 className="mt-3 text-2xl font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                              Whippy Ice Cream
                                                                                                                                                                                                                                                                                                                                                                                                                                          </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="mt-2 text-gray-200">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Freshly whipped soft ice cream with all your favourite toppings.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="rounded-3xl bg-white/10 backdrop-blur-md p-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="text-5xl">🍨</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 className="mt-3 text-2xl font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Luxury Sundaes
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="mt-2 text-gray-200">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Beautiful sundaes made fresh using premium sauces and toppings.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="rounded-3xl bg-white/10 backdrop-blur-md p-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="text-5xl">🥤</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="mt-3 text-2xl font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Ice Cold Slush
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="mt-2 text-gray-200">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Refreshing fruit slush available in a range of delicious flavours.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }