export default function WhyChoose() {
      const features = [
          {
                icon: "⭐",
                      title: "Serving the Midlands Since 2016",
                            text: "Years of experience providing unforgettable ice cream and slush for events of every size.",
                                },
                                    {
                                          icon: "🍦",
                                                title: "Premium Whippy Ice Cream",
                                                      text: "Delicious whippy ice cream, luxury sundaes and everyone's favourite classic treats.",
                                                          },
                                                              {
                                                                    icon: "❄️",
                                                                          title: "Premium Slush",
                                                                                text: "Refreshing premium slush in a range of vibrant flavours, perfect for hot summer days.",
                                                                                    },
                                                                                        {
                                                                                              icon: "🎉",
                                                                                                    title: "Events of Every Size",
                                                                                                          text: "Birthdays, weddings, schools, nurseries, corporate events and community celebrations.",
                                                                                                              },
                                                                                                                  {
                                                                                                                        icon: "😊",
                                                                                                                              title: "Friendly & Reliable",
                                                                                                                                    text: "We pride ourselves on arriving on time and providing excellent customer service every time.",
                                                                                                                                        },
                                                                                                                                            {
                                                                                                                                                  icon: "📍",
                                                                                                                                                        title: "Based in Walsall",
                                                                                                                                                              text: "Proudly serving Walsall and the surrounding West Midlands for private and public events.",
                                                                                                                                                                  },
                                                                                                                                                                    ];

                                                                                                                                                                      return (
                                                                                                                                                                          <section className="bg-white py-24">
                                                                                                                                                                                <div className="mx-auto max-w-7xl px-6">
                                                                                                                                                                                        <div className="mb-16 text-center">
                                                                                                                                                                                                  <div className="inline-flex h-12 items-center justify-center rounded-full bg-sky-100 px-6 text-sm font-semibold text-sky-700">
  Why Choose Bobby's?
</div>

                                                                                                                                                                                                                                  <h2 className="mt-6 text-5xl font-bold text-slate-800">
                                                                                                                                                                                                                                              Making Every Event Sweeter
                                                                                                                                                                                                                                                        </h2>

                                                                                                                                                                                                                                                                  <p className="mx-auto mt-6 max-w-3xl text-xl text-slate-600">
                                                                                                                                                                                                                                                                              We believe every celebration deserves amazing ice cream, refreshing
                                                                                                                                                                                                                                                                                          slush and friendly service that keeps your guests smiling.
                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                    <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
                                                                                                                                                                                                                                                                                                                              {features.map((feature) => (
                                                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                                                        key={feature.title}
                                                                                                                                                                                                                                                                                                                                                                      className="rounded-3xl border border-slate-200 bg-white p-8 shadow-lg transition duration-300 hover:-translate-y-2 hover:shadow-2xl"
                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                <div className="mb-5 text-5xl">{feature.icon}</div>

                                                                                                                                                                                                                                                                                                                                                                                                              <h3 className="mb-3 text-2xl font-bold text-slate-800">
                                                                                                                                                                                                                                                                                                                                                                                                                              {feature.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                            </h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="leading-7 text-slate-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {feature.text}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }